# Generated by Django 5.2.7 on 2025-10-16 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_card_last_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_benefits',
            field=models.TextField(max_length=350, null=True),
        ),
    ]
